language: csharp
os: linux
sudo: required
dist: xenial
addons:
  apt:
    packages:
    - gettext
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8
    - zlib1g
dotnet: 3.1
install:
  - dotnet restore
mono: latest
env:
  - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true DOTNET_CLI_TELEMETRY_OPTOUT=true

# You must run this command to give Travis permissions to execute the build.sh shell script:
# git update-index --chmod=+x build.sh
script:
  - ./build.sh
  - dotnet build
  - dotnet test tests/Exemplo.Identidade.API.Tests/Exemplo.Identidade.API.Tests.csproj